spring:
  config:
    activate:
      on-profile: in-memory
---
spring:
  config:
    activate:
      on-profile: in-memory
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:batch;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:13306/batch?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
      username: root
      password: root
  batch:
#    job:
#      enabled: false
    jdbc:
      initialize-schema: always